### ISSUE TITLE
How i can close this windows?

### ISSUE THREAD

**Issue by mannaggacardarell** [sawa90/AmongUsReplayInWindow#1]
I just opened the game and map appears on my screen but i can close it...

EDIT: I find a game and map is gone. But after game ends no replay and there's no folder where i can find it

**Comment by sawa90** [comment]
I have created a version that opens a console window.
If you get an error, could you please post the output of the console window? 
Also, I changed the location of the replay to the "AumongUsReplayInWindow" folder under the folder that contains the exe.
[AmongUsReplayInWindowV1.0.1_console.zip](https://github.com/sawa90/AmongUsReplayInWindow/files/5925609/AmongUsReplayInWindowV1.0.1_console.zip)

If it works well, the opened map can be closed by pressing the control key.
To exit the program, close the small window that opened first, or close Among Us.

**Comment by mannaggacardarell** [comment]
After this update works good. Btw i have a question, how i can close the replay? There's a hotkey? And, if possible, i think should be better if u add blur or shadow because he's not so clean to see

**Comment by sawa90** [comment]
To close the replay, press the control key while the Among Us window is active or the replay track bar has focus.
Sorry, you're right, the quality of the images is a bit poor. I will try to improve the appearance in the future. Thanks for the advice.
