### ISSUE TITLE
.NET Framework

### ISSUE THREAD

**Issue by jetstrike** [sawa90/AmongUsReplayInWindow#2]
I am prompted to install the .NET Framework when running the exe however it has already been installed.

**Comment by sawa90** [comment]
Sorry, I forgot that I had changed it to work only with 32bit.
It does not work with the x64 version of NET 5 Desktop Runtime.
Can you please install [the x86 version](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.3-windows-x86-installer) and then run the exe?
