### ISSUE TITLE
【要望】再生時の背景色を黒にできないでしょうか？

### ISSUE THREAD

**Issue by nobu02** [sawa90/AmongUsReplayInWindow#3]
素晴らしいツール開発、公開ありがとうございます。

以前までは下記のツールを使用していましたが新バージョンに対応しなくなってしまい、
検索したところ、こちらがヒットしました。
https://github.com/Smertig/among-us-replay-mod

障害ではなく要望なのですが、
単独再生時の背景色を黒、もしくはグレーにまたは、選択性にならないでしょうか？
白だと明るくて…
よかったら検討よろしくおねがいします。

**Comment by sawa90** [comment]
お使いいただきありがとうございます。
新しいバージョンから、背景色を変えられるようにしました。
遅くなってしまい申し訳ありません。

背景色の変更のみになり、文字色などはそのままですので少し見づらくなってしまうかもしれません。
今後なにか対策を考えようかとは思うのですが、申し訳ありませんがひとまずはこちらでお願いします。
ご要望ありがとうございました。

**Comment by nobu02** [comment]
背景色変更及び新バージョン対応ありがとうございます！！
