### ISSUE TITLE
【要望】スペースキーで一時停止/再生

### ISSUE THREAD

**Issue by nidixx** [sawa90/AmongUsReplayInWindow#4]
プレイログをじっくり検証したい時に、再生をちょっと止めておきたい時があります。
スペースキーで一時停止/再生ができれば便利かと思いました。
機能の実装をご検討いただけると嬉しいです。

**Comment by sawa90** [comment]
v2.0.0からスペースキーでの一時停止に対応しました。
大変遅くなり申し訳ありません。

**Comment by nidixx** [comment]
実装いただきありがとうございます！
